# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  proParser_config = debug
  proParser_test_config = debug

else ifeq ($(config),release)
  proParser_config = release
  proParser_test_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := proParser proParser_test

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

proParser:
ifneq (,$(proParser_config))
	@echo "==== Building proParser ($(proParser_config)) ===="
	@${MAKE} --no-print-directory -C . -f proParser.make config=$(proParser_config)
endif

proParser_test:
ifneq (,$(proParser_test_config))
	@echo "==== Building proParser_test ($(proParser_test_config)) ===="
	@${MAKE} --no-print-directory -C . -f proParser_test.make config=$(proParser_test_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f proParser.make clean
	@${MAKE} --no-print-directory -C . -f proParser_test.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   proParser"
	@echo "   proParser_test"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"